version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  node:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: node-test
    ports:
      - '3000:3000'
    depends_on:
      - mongo